package cn.sxwl.lvyou.common.entity;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aname
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.apassword
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private String apassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aname
     *
     * @return the value of admin.aname
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aname
     *
     * @param aname the value for admin.aname
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.apassword
     *
     * @return the value of admin.apassword
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String getApassword() {
        return apassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.apassword
     *
     * @param apassword the value for admin.apassword
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setApassword(String apassword) {
        this.apassword = apassword == null ? null : apassword.trim();
    }
}