package cn.sxwl.lvyou.common.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bid
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private Integer bid;
private List<Product> products;

    public List<Product> getProducts() {
        return products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bname
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private String bname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bpassword
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private String bpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.baddress
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private String baddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bemail
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private String bemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bcreatetime
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private Date bcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bbalance
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private BigDecimal bbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bcomment
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private String bcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bimg
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private String bimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bid
     *
     * @return the value of business.bid
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bid
     *
     * @param bid the value for business.bid
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bname
     *
     * @return the value of business.bname
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bname
     *
     * @param bname the value for business.bname
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bpassword
     *
     * @return the value of business.bpassword
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public String getBpassword() {
        return bpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bpassword
     *
     * @param bpassword the value for business.bpassword
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setBpassword(String bpassword) {
        this.bpassword = bpassword == null ? null : bpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.baddress
     *
     * @return the value of business.baddress
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public String getBaddress() {
        return baddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.baddress
     *
     * @param baddress the value for business.baddress
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setBaddress(String baddress) {
        this.baddress = baddress == null ? null : baddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bemail
     *
     * @return the value of business.bemail
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public String getBemail() {
        return bemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bemail
     *
     * @param bemail the value for business.bemail
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setBemail(String bemail) {
        this.bemail = bemail == null ? null : bemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bcreatetime
     *
     * @return the value of business.bcreatetime
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public Date getBcreatetime() {
        return bcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bcreatetime
     *
     * @param bcreatetime the value for business.bcreatetime
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setBcreatetime(Date bcreatetime) {
        this.bcreatetime = bcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bbalance
     *
     * @return the value of business.bbalance
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public BigDecimal getBbalance() {
        return bbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bbalance
     *
     * @param bbalance the value for business.bbalance
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setBbalance(BigDecimal bbalance) {
        this.bbalance = bbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bcomment
     *
     * @return the value of business.bcomment
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public String getBcomment() {
        return bcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bcomment
     *
     * @param bcomment the value for business.bcomment
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setBcomment(String bcomment) {
        this.bcomment = bcomment == null ? null : bcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bimg
     *
     * @return the value of business.bimg
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public String getBimg() {
        return bimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bimg
     *
     * @param bimg the value for business.bimg
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setBimg(String bimg) {
        this.bimg = bimg == null ? null : bimg.trim();
    }
}