package cn.sxwl.lvyou.common.entity;

import java.util.Date;

public class Choice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.cid
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.bid
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.pid
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.floor
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    private Integer floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.num
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.cdate
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    private String cdate;

    public String getBname() {
        return bname;
    }

    public void setBname(String bname) {
        this.bname = bname;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.enter
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    private Integer enter;

    private String bname;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.cid
     *
     * @return the value of choice.cid
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.cid
     *
     * @param cid the value for choice.cid
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.bid
     *
     * @return the value of choice.bid
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.bid
     *
     * @param bid the value for choice.bid
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.pid
     *
     * @return the value of choice.pid
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.pid
     *
     * @param pid the value for choice.pid
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.floor
     *
     * @return the value of choice.floor
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.floor
     *
     * @param floor the value for choice.floor
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.num
     *
     * @return the value of choice.num
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.num
     *
     * @param num the value for choice.num
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.cdate
     *
     * @return the value of choice.cdate
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public String getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.cdate
     *
     * @param cdate the value for choice.cdate
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public void setCdate(String cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.enter
     *
     * @return the value of choice.enter
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public Integer getEnter() {
        return enter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.enter
     *
     * @param enter the value for choice.enter
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public void setEnter(Integer enter) {
        this.enter = enter;
    }
}