package cn.sxwl.lvyou.common.entity;

public class Contact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contactid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private Integer contactid;

    @Override
    public String toString() {
        return "Contact{" +
                "contactid=" + contactid +
                ", content='" + content + '\'' +
                ", contactname='" + contactname + '\'' +
                ", contactemail='" + contactemail + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.content
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contactname
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private String contactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contactemail
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private String contactemail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contactid
     *
     * @return the value of contact.contactid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public Integer getContactid() {
        return contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contactid
     *
     * @param contactid the value for contact.contactid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setContactid(Integer contactid) {
        this.contactid = contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.content
     *
     * @return the value of contact.content
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.content
     *
     * @param content the value for contact.content
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contactname
     *
     * @return the value of contact.contactname
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contactname
     *
     * @param contactname the value for contact.contactname
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contactemail
     *
     * @return the value of contact.contactemail
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public String getContactemail() {
        return contactemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contactemail
     *
     * @param contactemail the value for contact.contactemail
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setContactemail(String contactemail) {
        this.contactemail = contactemail == null ? null : contactemail.trim();
    }
}