package cn.sxwl.lvyou.common.entity;

import java.math.BigDecimal;

public class Orderdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.oid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private String oid;
private  Scenic scenic;
private Product product;

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public Scenic getScenic() {
        return scenic;
    }

    public void setScenic(Scenic scenic) {
        this.scenic = scenic;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.sid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.pid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.onum
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private Integer onum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.oclass
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private String oclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.totprice
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private BigDecimal totprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.pl
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    private Integer pl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.oid
     *
     * @return the value of orderdetail.oid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.oid
     *
     * @param oid the value for orderdetail.oid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.sid
     *
     * @return the value of orderdetail.sid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.sid
     *
     * @param sid the value for orderdetail.sid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.pid
     *
     * @return the value of orderdetail.pid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.pid
     *
     * @param pid the value for orderdetail.pid
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.onum
     *
     * @return the value of orderdetail.onum
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public Integer getOnum() {
        return onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.onum
     *
     * @param onum the value for orderdetail.onum
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setOnum(Integer onum) {
        this.onum = onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.oclass
     *
     * @return the value of orderdetail.oclass
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public String getOclass() {
        return oclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.oclass
     *
     * @param oclass the value for orderdetail.oclass
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setOclass(String oclass) {
        this.oclass = oclass == null ? null : oclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.totprice
     *
     * @return the value of orderdetail.totprice
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public BigDecimal getTotprice() {
        return totprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.totprice
     *
     * @param totprice the value for orderdetail.totprice
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setTotprice(BigDecimal totprice) {
        this.totprice = totprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.pl
     *
     * @return the value of orderdetail.pl
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public Integer getPl() {
        return pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.pl
     *
     * @param pl the value for orderdetail.pl
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public void setPl(Integer pl) {
        this.pl = pl;
    }
}