package cn.sxwl.lvyou.common.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.oid
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private String oid;
private List<Orderdetail> orderdetail;

    public List<Orderdetail> getOrderdetail() {
        return orderdetail;
    }

    public void setOrderdetail(List<Orderdetail> orderdetail) {
        this.orderdetail = orderdetail;
    }

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.uid
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ocreatetime
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private Date ocreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.oprice
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private BigDecimal oprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.jiesuan
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    private Integer jiesuan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.oid
     *
     * @return the value of orders.oid
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.oid
     *
     * @param oid the value for orders.oid
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.uid
     *
     * @return the value of orders.uid
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.uid
     *
     * @param uid the value for orders.uid
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ocreatetime
     *
     * @return the value of orders.ocreatetime
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public Date getOcreatetime() {
        return ocreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ocreatetime
     *
     * @param ocreatetime the value for orders.ocreatetime
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setOcreatetime(Date ocreatetime) {
        this.ocreatetime = ocreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.oprice
     *
     * @return the value of orders.oprice
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public BigDecimal getOprice() {
        return oprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.oprice
     *
     * @param oprice the value for orders.oprice
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setOprice(BigDecimal oprice) {
        this.oprice = oprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.jiesuan
     *
     * @return the value of orders.jiesuan
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public Integer getJiesuan() {
        return jiesuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.jiesuan
     *
     * @param jiesuan the value for orders.jiesuan
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public void setJiesuan(Integer jiesuan) {
        this.jiesuan = jiesuan;
    }
}