package cn.sxwl.lvyou.common.entity;

import java.math.BigDecimal;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    private Integer pid;

    @Override
    public String toString() {
        return "Product{" +
                "pid=" + pid +
                ", bid=" + bid +
                ", pname='" + pname + '\'' +
                ", pimg='" + pimg + '\'' +
                ", pprice=" + pprice +
                ", pup=" + pup +
                ", pdiscount=" + pdiscount +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.bid
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pimg
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    private String pimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pprice
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    private BigDecimal pprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pup
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    private Integer pup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pdiscount
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    private BigDecimal pdiscount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.bid
     *
     * @return the value of product.bid
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.bid
     *
     * @param bid the value for product.bid
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pimg
     *
     * @return the value of product.pimg
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public String getPimg() {
        return pimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pimg
     *
     * @param pimg the value for product.pimg
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public void setPimg(String pimg) {
        this.pimg = pimg == null ? null : pimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pprice
     *
     * @return the value of product.pprice
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public BigDecimal getPprice() {
        return pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pprice
     *
     * @param pprice the value for product.pprice
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public void setPprice(BigDecimal pprice) {
        this.pprice = pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pup
     *
     * @return the value of product.pup
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public Integer getPup() {
        return pup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pup
     *
     * @param pup the value for product.pup
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public void setPup(Integer pup) {
        this.pup = pup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pdiscount
     *
     * @return the value of product.pdiscount
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public BigDecimal getPdiscount() {
        return pdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pdiscount
     *
     * @param pdiscount the value for product.pdiscount
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public void setPdiscount(BigDecimal pdiscount) {
        this.pdiscount = pdiscount;
    }
}