package cn.sxwl.lvyou.common.entity;

import java.math.BigDecimal;

public class Scenic {
    @Override
    public String toString() {
        return "Scenic{" +
                "sid=" + sid +
                ", sname='" + sname + '\'' +
                ", saddress='" + saddress + '\'' +
                ", sprice=" + sprice +
                ", simg='" + simg + '\'' +
                ", sstudent=" + sstudent +
                ", scomment='" + scomment + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.sid
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.sname
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.saddress
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private String saddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.sprice
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private BigDecimal sprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.simg
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private String simg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.sstudent
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private BigDecimal sstudent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scomment
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private String scomment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.sid
     *
     * @return the value of scenic.sid
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.sid
     *
     * @param sid the value for scenic.sid
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.sname
     *
     * @return the value of scenic.sname
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.sname
     *
     * @param sname the value for scenic.sname
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.saddress
     *
     * @return the value of scenic.saddress
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String getSaddress() {
        return saddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.saddress
     *
     * @param saddress the value for scenic.saddress
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setSaddress(String saddress) {
        this.saddress = saddress == null ? null : saddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.sprice
     *
     * @return the value of scenic.sprice
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public BigDecimal getSprice() {
        return sprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.sprice
     *
     * @param sprice the value for scenic.sprice
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setSprice(BigDecimal sprice) {
        this.sprice = sprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.simg
     *
     * @return the value of scenic.simg
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String getSimg() {
        return simg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.simg
     *
     * @param simg the value for scenic.simg
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setSimg(String simg) {
        this.simg = simg == null ? null : simg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.sstudent
     *
     * @return the value of scenic.sstudent
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public BigDecimal getSstudent() {
        return sstudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.sstudent
     *
     * @param sstudent the value for scenic.sstudent
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setSstudent(BigDecimal sstudent) {
        this.sstudent = sstudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scomment
     *
     * @return the value of scenic.scomment
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String getScomment() {
        return scomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scomment
     *
     * @param scomment the value for scenic.scomment
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setScomment(String scomment) {
        this.scomment = scomment == null ? null : scomment.trim();
    }
}