package cn.sxwl.lvyou.common.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class User {
    public List<Orders> getOrders() {
        return orders;
    }

    @Override
    public String toString() {
        return "User{" +
                "uid=" + uid +
                ", uname='" + uname + '\'' +
                ", upassword='" + upassword + '\'' +
                ", uaddress='" + uaddress + '\'' +
                ", uemail='" + uemail + '\'' +
                ", ucreatetime=" + ucreatetime +
                ", ubalance=" + ubalance +
                ", uhead='" + uhead + '\'' +
                ", orders=" + orders +
                '}';
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *

     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upassword
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private String upassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uaddress
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private String uaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uemail
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private String uemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ucreatetime
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    private Date ucreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ubalance
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
            */
    private BigDecimal ubalance;



    private String uhead;
    private List<Orders> orders;
    public void setOrders(List<Orders> orders) {
        this.orders = orders;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upassword
     *
     * @return the value of user.upassword
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String getUpassword() {
        return upassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upassword
     *
     * @param upassword the value for user.upassword
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setUpassword(String upassword) {
        this.upassword = upassword == null ? null : upassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uaddress
     *
     * @return the value of user.uaddress
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String getUaddress() {
        return uaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uaddress
     *
     * @param uaddress the value for user.uaddress
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setUaddress(String uaddress) {
        this.uaddress = uaddress == null ? null : uaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uemail
     *
     * @return the value of user.uemail
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uemail
     *
     * @param uemail the value for user.uemail
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setUemail(String uemail) {
        this.uemail = uemail == null ? null : uemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ucreatetime
     *
     * @return the value of user.ucreatetime
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public Date getUcreatetime() {
        return ucreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ucreatetime
     *
     * @param ucreatetime the value for user.ucreatetime
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setUcreatetime(Date ucreatetime) {
        this.ucreatetime = ucreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ubalance
     *
     * @return the value of user.ubalance
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public BigDecimal getUbalance() {
        return ubalance;
    }

    public String getUhead() {
        return uhead;
    }

    public void setUhead(String uhead) {
        this.uhead = uhead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ubalance
     *
     * @param ubalance the value for user.ubalance
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public void setUbalance(BigDecimal ubalance) {
        this.ubalance = ubalance;
    }
}