package cn.sxwl.lvyou.common.dao;

import cn.sxwl.lvyou.common.entity.Admin;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Component
public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    @Delete({
        "delete from admin",
        "where aname = #{aname,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String aname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    @Insert({
        "insert into admin (aname, apassword)",
        "values (#{aname,jdbcType=VARCHAR}, #{apassword,jdbcType=VARCHAR})"
    })
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    @InsertProvider(type=AdminSqlProvider.class, method="insertSelective")
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    @Select({
        "select",
        "aname, apassword",
        "from admin",
        "where aname = #{aname,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="aname", property="aname", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="apassword", property="apassword", jdbcType=JdbcType.VARCHAR)
    })
    Admin selectByPrimaryKey(String aname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    @UpdateProvider(type=AdminSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    @Update({
        "update admin",
        "set apassword = #{apassword,jdbcType=VARCHAR}",
        "where aname = #{aname,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Admin record);
}