package cn.sxwl.lvyou.common.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.sxwl.lvyou.common.entity.Admin;

public class AdminSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String insertSelective(Admin record) {
        BEGIN();
        INSERT_INTO("admin");
        
        if (record.getAname() != null) {
            VALUES("aname", "#{aname,jdbcType=VARCHAR}");
        }
        
        if (record.getApassword() != null) {
            VALUES("apassword", "#{apassword,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Admin record) {
        BEGIN();
        UPDATE("admin");
        
        if (record.getApassword() != null) {
            SET("apassword = #{apassword,jdbcType=VARCHAR}");
        }
        
        WHERE("aname = #{aname,jdbcType=VARCHAR}");
        
        return SQL();
    }
}