package cn.sxwl.lvyou.common.dao;


import cn.sxwl.lvyou.common.entity.Business;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class BusinessSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public String insertSelective(Business record) {
        BEGIN();
        INSERT_INTO("business");
        
        if (record.getBid() != null) {
            VALUES("bid", "#{bid,jdbcType=INTEGER}");
        }
        
        if (record.getBname() != null) {
            VALUES("bname", "#{bname,jdbcType=VARCHAR}");
        }
        
        if (record.getBpassword() != null) {
            VALUES("bpassword", "#{bpassword,jdbcType=VARCHAR}");
        }
        
        if (record.getBaddress() != null) {
            VALUES("baddress", "#{baddress,jdbcType=VARCHAR}");
        }
        
        if (record.getBemail() != null) {
            VALUES("bemail", "#{bemail,jdbcType=VARCHAR}");
        }
        
        if (record.getBcreatetime() != null) {
            VALUES("bcreatetime", "#{bcreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getBbalance() != null) {
            VALUES("bbalance", "#{bbalance,jdbcType=DECIMAL}");
        }
        
        if (record.getBcomment() != null) {
            VALUES("bcomment", "#{bcomment,jdbcType=VARCHAR}");
        }
        
        if (record.getBimg() != null) {
            VALUES("bimg", "#{bimg,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Sun Feb 10 12:45:23 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Business record) {
        BEGIN();
        UPDATE("business");
        
        if (record.getBname() != null) {
            SET("bname = #{bname,jdbcType=VARCHAR}");
        }
        
        if (record.getBpassword() != null) {
            SET("bpassword = #{bpassword,jdbcType=VARCHAR}");
        }
        
        if (record.getBaddress() != null) {
            SET("baddress = #{baddress,jdbcType=VARCHAR}");
        }
        
        if (record.getBemail() != null) {
            SET("bemail = #{bemail,jdbcType=VARCHAR}");
        }
        
        if (record.getBcreatetime() != null) {
            SET("bcreatetime = #{bcreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getBbalance() != null) {
            SET("bbalance = #{bbalance,jdbcType=DECIMAL}");
        }
        
        if (record.getBcomment() != null) {
            SET("bcomment = #{bcomment,jdbcType=VARCHAR}");
        }
        
        if (record.getBimg() != null) {
            SET("bimg = #{bimg,jdbcType=VARCHAR}");
        }
        
        WHERE("bid = #{bid,jdbcType=INTEGER}");
        
        return SQL();
    }
}