package cn.sxwl.lvyou.common.dao;


import cn.sxwl.lvyou.common.entity.Choice;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Component
public interface ChoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    @Delete({
        "delete from choice",
        "where cid = #{cid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    @Insert({
        "insert into choice (cid, bid, ",
        "pid, floor, num, ",
        "cdate, enter)",
        "values (#{cid,jdbcType=INTEGER}, #{bid,jdbcType=INTEGER}, ",
        "#{pid,jdbcType=INTEGER}, #{floor,jdbcType=INTEGER}, #{num,jdbcType=INTEGER}, ",
        "#{cdate,jdbcType=VARCHAR}, #{enter,jdbcType=INTEGER})"
    })
    int insert(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    @InsertProvider(type=ChoiceSqlProvider.class, method="insertSelective")
    int insertSelective(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    @Select({
        "select",
        "cid, bid, pid, floor, num, cdate, enter",
        "from choice",
        "where cid = #{cid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="cid", property="cid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="bid", property="bid", jdbcType=JdbcType.INTEGER),
        @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER),
        @Result(column="floor", property="floor", jdbcType=JdbcType.INTEGER),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="cdate", property="cdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="enter", property="enter", jdbcType=JdbcType.INTEGER)
    })
    Choice selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    @UpdateProvider(type=ChoiceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    @Update({
        "update choice",
        "set bid = #{bid,jdbcType=INTEGER},",
          "pid = #{pid,jdbcType=INTEGER},",
          "floor = #{floor,jdbcType=INTEGER},",
          "num = #{num,jdbcType=INTEGER},",
          "cdate = #{cdate,jdbcType=VARCHAR},",
          "enter = #{enter,jdbcType=INTEGER}",
        "where cid = #{cid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Choice record);

    @Select({
            "select",
            "cid, bid, pid, floor, num, cdate, enter",
            "from choice",
            "where bid = #{bid,jdbcType=INTEGER} and cdate = #{cdate,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="cid", property="cid", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="bid", property="bid", jdbcType=JdbcType.INTEGER),
            @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER),
            @Result(column="floor", property="floor", jdbcType=JdbcType.INTEGER),
            @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
            @Result(column="cdate", property="cdate", jdbcType=JdbcType.VARCHAR),
            @Result(column="enter", property="enter", jdbcType=JdbcType.INTEGER),
            @Result(column = "bid",property = "bname",one = @One(select = "cn.sxwl.lvyou.common.dao.BusinessMapper.selectBusinessName"))
    })
    List<Choice> selectByBidDate(@Param("bid")Integer bid,@Param("cdate") String cdate);

}