package cn.sxwl.lvyou.common.dao;


import cn.sxwl.lvyou.common.entity.Choice;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class ChoiceSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public String insertSelective(Choice record) {
        BEGIN();
        INSERT_INTO("choice");
        
        if (record.getCid() != null) {
            VALUES("cid", "#{cid,jdbcType=INTEGER}");
        }
        
        if (record.getBid() != null) {
            VALUES("bid", "#{bid,jdbcType=INTEGER}");
        }
        
        if (record.getPid() != null) {
            VALUES("pid", "#{pid,jdbcType=INTEGER}");
        }
        
        if (record.getFloor() != null) {
            VALUES("floor", "#{floor,jdbcType=INTEGER}");
        }
        
        if (record.getNum() != null) {
            VALUES("num", "#{num,jdbcType=INTEGER}");
        }
        
        if (record.getCdate() != null) {
            VALUES("cdate", "#{cdate,jdbcType=DATE}");
        }
        
        if (record.getEnter() != null) {
            VALUES("enter", "#{enter,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Sat Mar 02 14:49:11 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Choice record) {
        BEGIN();
        UPDATE("choice");
        
        if (record.getBid() != null) {
            SET("bid = #{bid,jdbcType=INTEGER}");
        }
        
        if (record.getPid() != null) {
            SET("pid = #{pid,jdbcType=INTEGER}");
        }
        
        if (record.getFloor() != null) {
            SET("floor = #{floor,jdbcType=INTEGER}");
        }
        
        if (record.getNum() != null) {
            SET("num = #{num,jdbcType=INTEGER}");
        }
        
        if (record.getCdate() != null) {
            SET("cdate = #{cdate,jdbcType=DATE}");
        }
        
        if (record.getEnter() != null) {
            SET("enter = #{enter,jdbcType=INTEGER}");
        }
        
        WHERE("cid = #{cid,jdbcType=INTEGER}");
        
        return SQL();
    }
}