package cn.sxwl.lvyou.common.dao;

import cn.sxwl.lvyou.common.entity.Orderdetail;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;


public class OrderdetailSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    public String insertSelective(Orderdetail record) {
        BEGIN();
        INSERT_INTO("orderdetail");
        
        if (record.getOid() != null) {
            VALUES("oid", "#{oid,jdbcType=VARCHAR}");
        }
        
        if (record.getSid() != null) {
            VALUES("sid", "#{sid,jdbcType=INTEGER}");
        }
        
        if (record.getPid() != null) {
            VALUES("pid", "#{pid,jdbcType=INTEGER}");
        }
        
        if (record.getOnum() != null) {
            VALUES("onum", "#{onum,jdbcType=INTEGER}");
        }
        
        if (record.getOclass() != null) {
            VALUES("oclass", "#{oclass,jdbcType=VARCHAR}");
        }
        
        if (record.getTotprice() != null) {
            VALUES("totprice", "#{totprice,jdbcType=DECIMAL}");
        }
        
        if (record.getPl() != null) {
            VALUES("pl", "#{pl,jdbcType=INTEGER}");
        }
        
        return SQL();
    }
}