package cn.sxwl.lvyou.common.dao;

import cn.sxwl.lvyou.common.entity.Orderdetail;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;

public interface OrderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    @Insert({
        "insert into orderdetail (oid, sid, ",
        "pid, onum, oclass, ",
        "totprice, pl)",
        "values (#{oid,jdbcType=VARCHAR}, #{sid,jdbcType=INTEGER}, ",
        "#{pid,jdbcType=INTEGER}, #{onum,jdbcType=INTEGER}, #{oclass,jdbcType=VARCHAR}, ",
        "#{totprice,jdbcType=DECIMAL}, #{pl,jdbcType=INTEGER})"
    })
    int insert(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Mon Mar 11 19:56:18 GMT+08:00 2019
     */
    @InsertProvider(type=OrderdetailSqlProvider.class, method="insertSelective")
    int insertSelective(Orderdetail record);
}