package cn.sxwl.lvyou.common.dao;

import cn.sxwl.lvyou.common.entity.Product;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;


public class ProductSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public String insertSelective(Product record) {
        BEGIN();
        INSERT_INTO("product");
        
        if (record.getPid() != null) {
            VALUES("pid", "#{pid,jdbcType=INTEGER}");
        }
        
        if (record.getBid() != null) {
            VALUES("bid", "#{bid,jdbcType=INTEGER}");
        }
        
        if (record.getPname() != null) {
            VALUES("pname", "#{pname,jdbcType=VARCHAR}");
        }
        
        if (record.getPimg() != null) {
            VALUES("pimg", "#{pimg,jdbcType=VARCHAR}");
        }
        
        if (record.getPprice() != null) {
            VALUES("pprice", "#{pprice,jdbcType=DECIMAL}");
        }
        
        if (record.getPup() != null) {
            VALUES("pup", "#{pup,jdbcType=INTEGER}");
        }
        
        if (record.getPdiscount() != null) {
            VALUES("pdiscount", "#{pdiscount,jdbcType=DECIMAL}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Mar 07 20:02:41 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Product record) {
        BEGIN();
        UPDATE("product");
        
        if (record.getBid() != null) {
            SET("bid = #{bid,jdbcType=INTEGER}");
        }
        
        if (record.getPname() != null) {
            SET("pname = #{pname,jdbcType=VARCHAR}");
        }
        
        if (record.getPimg() != null) {
            SET("pimg = #{pimg,jdbcType=VARCHAR}");
        }
        
        if (record.getPprice() != null) {
            SET("pprice = #{pprice,jdbcType=DECIMAL}");
        }
        
        if (record.getPup() != null) {
            SET("pup = #{pup,jdbcType=INTEGER}");
        }
        
        if (record.getPdiscount() != null) {
            SET("pdiscount = #{pdiscount,jdbcType=DECIMAL}");
        }
        
        WHERE("pid = #{pid,jdbcType=INTEGER}");
        
        return SQL();
    }
}