package cn.sxwl.lvyou.common.dao;

import cn.sxwl.lvyou.common.entity.User;
import org.apache.ibatis.jdbc.SQL;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class UserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String insertSelective(User record) {
        BEGIN();
        INSERT_INTO("user");
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        if (record.getUname() != null) {
            VALUES("uname", "#{uname,jdbcType=VARCHAR}");
        }
        
        if (record.getUpassword() != null) {
            VALUES("upassword", "#{upassword,jdbcType=VARCHAR}");
        }
        
        if (record.getUaddress() != null) {
            VALUES("uaddress", "#{uaddress,jdbcType=VARCHAR}");
        }
        
        if (record.getUemail() != null) {
            VALUES("uemail", "#{uemail,jdbcType=VARCHAR}");
        }
        
        if (record.getUcreatetime() != null) {
            VALUES("ucreatetime", "#{ucreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUbalance() != null) {
            VALUES("ubalance", "#{ubalance,jdbcType=DECIMAL}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jan 20 13:02:47 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(User record) {
        BEGIN();
        UPDATE("user");
        
        if (record.getUname() != null) {
            SET("uname = #{uname,jdbcType=VARCHAR}");
        }
        
        if (record.getUpassword() != null) {
            SET("upassword = #{upassword,jdbcType=VARCHAR}");
        }
        
        if (record.getUaddress() != null) {
            SET("uaddress = #{uaddress,jdbcType=VARCHAR}");
        }
        
        if (record.getUemail() != null) {
            SET("uemail = #{uemail,jdbcType=VARCHAR}");
        }
        
        if (record.getUcreatetime() != null) {
            SET("ucreatetime = #{ucreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUbalance() != null) {
            SET("ubalance = #{ubalance,jdbcType=DECIMAL}");
        }
        
        WHERE("uid = #{uid,jdbcType=INTEGER}");
        
        return SQL();
    }

    public String testSelect(String tiaojian){
        BEGIN();
        if (tiaojian.equals("one")) {
            SELECT("uname,uaddress");
            FROM("user");
        }
        else if (!tiaojian.equals("one")){
            SELECT("uname,uaddress,oprice");
            FROM("orders,user");
            WHERE("orders.uid=user.uid and user.uid=#{two}");
        }
        return SQL();
    }
}